-- BLOCK 08: INDEXES (idempotente)
CREATE INDEX IF NOT EXISTS idx_agent_achievements_profile ON public.agent_achievements USING btree (profile_id);
CREATE INDEX IF NOT EXISTS idx_agent_stats_level ON public.agent_stats USING btree (level DESC);
CREATE INDEX IF NOT EXISTS idx_agent_stats_xp ON public.agent_stats USING btree (xp DESC);
CREATE INDEX IF NOT EXISTS idx_ai_usage_logs_created_at ON public.ai_usage_logs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_usage_logs_function_name ON public.ai_usage_logs USING btree (function_name);
CREATE INDEX IF NOT EXISTS idx_ai_usage_logs_profile_id ON public.ai_usage_logs USING btree (profile_id);
CREATE INDEX IF NOT EXISTS idx_ai_usage_logs_status ON public.ai_usage_logs USING btree (status);
CREATE INDEX IF NOT EXISTS idx_ai_usage_logs_user_id ON public.ai_usage_logs USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_allowed_countries_code ON public.allowed_countries USING btree (country_code);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON public.audit_logs USING btree (action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.audit_logs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_created ON public.audit_logs USING btree (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON public.audit_logs USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_blocked_countries_code ON public.blocked_countries USING btree (country_code);
CREATE INDEX IF NOT EXISTS idx_blocked_ips_expires ON public.blocked_ips USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_blocked_ips_ip ON public.blocked_ips USING btree (ip_address);
CREATE INDEX IF NOT EXISTS idx_business_hours_connection ON public.business_hours USING btree (whatsapp_connection_id);
CREATE INDEX IF NOT EXISTS idx_campaign_contacts_campaign ON public.campaign_contacts USING btree (campaign_id, status);
CREATE INDEX IF NOT EXISTS idx_campaign_contacts_campaign_id ON public.campaign_contacts USING btree (campaign_id);
CREATE INDEX IF NOT EXISTS idx_campaign_contacts_status ON public.campaign_contacts USING btree (status);
CREATE INDEX IF NOT EXISTS idx_campaigns_created_by ON public.campaigns USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_campaigns_status ON public.campaigns USING btree (status);
CREATE INDEX IF NOT EXISTS idx_chatbot_executions_contact_id ON public.chatbot_executions USING btree (contact_id);
CREATE INDEX IF NOT EXISTS idx_chatbot_executions_flow_id ON public.chatbot_executions USING btree (flow_id);
CREATE INDEX IF NOT EXISTS idx_chatbot_executions_status ON public.chatbot_executions USING btree (status);
CREATE INDEX IF NOT EXISTS idx_chatbot_flows_active ON public.chatbot_flows USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_closures_contact ON public.conversation_closures USING btree (contact_id);
CREATE INDEX IF NOT EXISTS idx_closures_reason ON public.conversation_closures USING btree (close_reason);
CREATE INDEX IF NOT EXISTS idx_contact_custom_fields_contact ON public.contact_custom_fields USING btree (contact_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_contact_custom_fields_unique ON public.contact_custom_fields USING btree (contact_id, field_name);
CREATE INDEX IF NOT EXISTS idx_contact_notes_author_id ON public.contact_notes USING btree (author_id);
CREATE INDEX IF NOT EXISTS idx_contact_notes_contact_id ON public.contact_notes USING btree (contact_id);
CREATE INDEX IF NOT EXISTS idx_contacts_assigned_to ON public.contacts USING btree (assigned_to);
CREATE INDEX IF NOT EXISTS idx_contacts_company_trgm ON public.contacts USING gin (company extensions.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_contacts_contact_type ON public.contacts USING btree (contact_type);
CREATE INDEX IF NOT EXISTS idx_contacts_created_at ON public.contacts USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_contacts_email_trgm ON public.contacts USING gin (email extensions.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_contacts_job_title_trgm ON public.contacts USING gin (job_title extensions.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_contacts_name_asc ON public.contacts USING btree (name);
CREATE INDEX IF NOT EXISTS idx_contacts_name_trgm ON public.contacts USING gin (name extensions.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_contacts_nickname_trgm ON public.contacts USING gin (nickname extensions.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_contacts_phone_trgm ON public.contacts USING gin (phone extensions.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_contacts_queue_id ON public.contacts USING btree (queue_id);
CREATE INDEX IF NOT EXISTS idx_contacts_surname_trgm ON public.contacts USING gin (surname extensions.gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_contacts_type ON public.contacts USING btree (contact_type);
CREATE INDEX IF NOT EXISTS idx_conversation_analyses_contact_department ON public.conversation_analyses USING btree (contact_id, department);
CREATE INDEX IF NOT EXISTS idx_conversation_analyses_contact_id ON public.conversation_analyses USING btree (contact_id);
CREATE INDEX IF NOT EXISTS idx_conversation_analyses_created_at ON public.conversation_analyses USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversation_analyses_department ON public.conversation_analyses USING btree (department);
CREATE INDEX IF NOT EXISTS idx_conversation_events_contact ON public.conversation_events USING btree (contact_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversation_events_type ON public.conversation_events USING btree (event_type);
CREATE INDEX IF NOT EXISTS idx_email_labels_account ON public.email_labels USING btree (gmail_account_id);
CREATE INDEX IF NOT EXISTS idx_email_messages_account ON public.email_messages USING btree (gmail_account_id);
CREATE INDEX IF NOT EXISTS idx_email_messages_date ON public.email_messages USING btree (internal_date DESC);
CREATE INDEX IF NOT EXISTS idx_email_messages_thread ON public.email_messages USING btree (thread_id);
CREATE INDEX IF NOT EXISTS idx_email_threads_account ON public.email_threads USING btree (gmail_account_id);
CREATE INDEX IF NOT EXISTS idx_email_threads_contact ON public.email_threads USING btree (contact_id);
CREATE INDEX IF NOT EXISTS idx_email_threads_last_message ON public.email_threads USING btree (last_message_at DESC);
CREATE INDEX IF NOT EXISTS idx_health_logs_checked_at ON public.connection_health_logs USING btree (checked_at DESC);
CREATE INDEX IF NOT EXISTS idx_health_logs_connection_checked ON public.connection_health_logs USING btree (connection_id, checked_at DESC);
CREATE INDEX IF NOT EXISTS idx_kb_articles_search ON public.knowledge_base_articles USING gin (search_vector);
CREATE INDEX IF NOT EXISTS idx_login_attempts_email ON public.login_attempts USING btree (email);
CREATE INDEX IF NOT EXISTS idx_login_attempts_locked ON public.login_attempts USING btree (locked_until) WHERE (locked_until IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_message_reactions_message ON public.message_reactions USING btree (message_id);
CREATE INDEX IF NOT EXISTS idx_messages_contact_created ON public.messages USING btree (contact_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_contact_id ON public.messages USING btree (contact_id);
CREATE INDEX IF NOT EXISTS idx_messages_content_search ON public.messages USING gin (to_tsvector('portuguese'::regconfig, content));
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON public.messages USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_external_id ON public.messages USING btree (external_id);
CREATE INDEX IF NOT EXISTS idx_mfa_sessions_user ON public.mfa_sessions USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON public.notifications USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON public.notifications USING btree (is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_nps_surveys_contact ON public.nps_surveys USING btree (contact_id);
CREATE INDEX IF NOT EXISTS idx_nps_surveys_created ON public.nps_surveys USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_passkey_credentials_credential_id ON public.passkey_credentials USING btree (credential_id);
CREATE INDEX IF NOT EXISTS idx_passkey_credentials_user_id ON public.passkey_credentials USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_password_reset_requests_status ON public.password_reset_requests USING btree (status);
CREATE INDEX IF NOT EXISTS idx_password_reset_requests_user ON public.password_reset_requests USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_performance_snapshots_created_at ON public.performance_snapshots USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_performance_snapshots_profile ON public.performance_snapshots USING btree (profile_id);
CREATE INDEX IF NOT EXISTS idx_products_active ON public.products USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products USING btree (category);
CREATE INDEX IF NOT EXISTS idx_profiles_is_active ON public.profiles USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_query_telemetry_created_at ON public.query_telemetry USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_query_telemetry_severity ON public.query_telemetry USING btree (severity);
CREATE INDEX IF NOT EXISTS idx_rate_limit_logs_created ON public.rate_limit_logs USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_rate_limit_logs_ip ON public.rate_limit_logs USING btree (ip_address);
CREATE INDEX IF NOT EXISTS idx_rate_limit_logs_user ON public.rate_limit_logs USING btree (user_id);