-- BLOCK 08 (parte 2): índices remanescentes
CREATE INDEX IF NOT EXISTS idx_rate_limits_instance_window ON public.webhook_rate_limits USING btree (instance_id, window_start DESC);
CREATE INDEX IF NOT EXISTS idx_reminders_profile ON public.reminders USING btree (profile_id);
CREATE INDEX IF NOT EXISTS idx_reminders_remind_at ON public.reminders USING btree (remind_at);
CREATE INDEX IF NOT EXISTS idx_reputation_connection ON public.number_reputation USING btree (whatsapp_connection_id);
CREATE INDEX IF NOT EXISTS idx_saved_filters_user_entity ON public.saved_filters USING btree (user_id, entity_type);
CREATE INDEX IF NOT EXISTS idx_scheduled_messages_pending ON public.scheduled_messages USING btree (scheduled_at) WHERE (status = 'pending'::text);
CREATE INDEX IF NOT EXISTS idx_security_alerts_created ON public.security_alerts USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_security_alerts_type ON public.security_alerts USING btree (alert_type);
CREATE INDEX IF NOT EXISTS idx_sla_rules_active ON public.sla_rules USING btree (is_active) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_sla_rules_active_priority ON public.sla_rules USING btree (is_active, priority DESC);
CREATE INDEX IF NOT EXISTS idx_sla_rules_agent_id ON public.sla_rules USING btree (agent_id) WHERE (agent_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_sla_rules_company ON public.sla_rules USING btree (company) WHERE (company IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_sla_rules_contact_id ON public.sla_rules USING btree (contact_id) WHERE (contact_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_sla_rules_queue_id ON public.sla_rules USING btree (queue_id) WHERE (queue_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_snoozes_contact ON public.conversation_snoozes USING btree (contact_id);
CREATE INDEX IF NOT EXISTS idx_snoozes_until ON public.conversation_snoozes USING btree (snooze_until);
CREATE INDEX IF NOT EXISTS idx_stickers_owner_id ON public.stickers USING btree (owner_id) WHERE (owner_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_talkx_blacklist_contact ON public.talkx_blacklist USING btree (contact_id);
CREATE INDEX IF NOT EXISTS idx_talkx_campaigns_created_by ON public.talkx_campaigns USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_talkx_campaigns_status ON public.talkx_campaigns USING btree (status);
CREATE INDEX IF NOT EXISTS idx_talkx_recipients_campaign ON public.talkx_recipients USING btree (campaign_id);
CREATE INDEX IF NOT EXISTS idx_talkx_recipients_status ON public.talkx_recipients USING btree (status);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned ON public.conversation_tasks USING btree (assigned_to);
CREATE INDEX IF NOT EXISTS idx_tasks_contact ON public.conversation_tasks USING btree (contact_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON public.conversation_tasks USING btree (status);
CREATE INDEX IF NOT EXISTS idx_team_members_conversation ON public.team_conversation_members USING btree (conversation_id);
CREATE INDEX IF NOT EXISTS idx_team_members_profile ON public.team_conversation_members USING btree (profile_id);
CREATE INDEX IF NOT EXISTS idx_team_messages_conversation ON public.team_messages USING btree (conversation_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_devices_fingerprint ON public.user_devices USING btree (device_fingerprint);
CREATE INDEX IF NOT EXISTS idx_user_devices_user_id ON public.user_devices USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_user_sessions_active ON public.user_sessions USING btree (is_active) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id ON public.user_sessions USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_versions_date ON public.entity_versions USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_versions_entity ON public.entity_versions USING btree (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_voice_command_logs_created_at ON public.voice_command_logs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_voice_command_logs_user_id ON public.voice_command_logs USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_webauthn_challenges_expires ON public.webauthn_challenges USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_whatsapp_groups_category ON public.whatsapp_groups USING btree (category);