// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://rqmbchomazwsaupnuduf.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxbWJjaG9tYXp3c2F1cG51ZHVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxMDIyODgsImV4cCI6MjA5MTY3ODI4OH0.TY6YQ5pDHixxzz1B_SDiPK76ajYjerDgzE8gEbIdyX4';

// Log status but don't crash the entire bundle
if (!import.meta.env.VITE_SUPABASE_URL) {
  console.warn("Supabase environment variables are missing! Using fallback URL.");
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});